// IMPORT
/* HEADER */
/* PREMIUM */
/* HEADER */
/* SERVICES */
/* COMMUNICATION */
/* DEVICE MANAGER */
/* sAps WORKS */
/* ITERFACE START */
/* OUR REVIEW */
/* PRICE LIST */
/* FAQ */
/* TEAM EXPERTS */
/* SUBSCRIBE */
/* STAY STAR */
/* AVALIBLE START */
/* FOOTER */

// FUNKCIJU PANAUDOJIMAS
/* HEADER */
/* PREMIUM */
/* HEADER */
/* SERVICES */
/* COMMUNICATION */
/* DEVICE MANAGER */
/* sAps WORKS */
/* ITERFACE START */
/* OUR REVIEW */
/* PRICE LIST */
/* FAQ */
/* TEAM EXPERTS */
/* SUBSCRIBE */
/* STAY STAR */
/* AVALIBLE START */
/* FOOTER */