// IMPORT
/* HEADER */
/* HERO */
/* ACHIEVEMENTS */
/* SERVICES */
/* DEVICE MANAGER */
/* COMMUNICATION */
/* sAps WORKS */
/* ITERFACE START */
/* OUR REVIEW */
/* PRICE LIST */
/* FAQ */
/* TEAM EXPERTS */
/* AVAILABLE START */
/* SUBSCRIBE */
/* STAY STAR */
/* FOOTER */

// FUNKCIJU PANAUDOJIMAS
/* HEADER */
/* HERO */
/* ACHIEVEMENTS */
/* SERVICES */
/* DEVICE MANAGER */
/* COMMUNICATION */
/* sAps WORKS */
/* ITERFACE START */
/* OUR REVIEW */
/* PRICE LIST */
/* FAQ */
/* TEAM EXPERTS */
/* AVAILABLE START */
/* SUBSCRIBE */
/* STAY STAR */
/* FOOTER */